GET http://{{ASSET_MANTLE_CLIENT_HOST}}:{{ASSET_MANTLE_CLIENT_PORT}}/metas/metas/S.HOYjRNrcrmgC3apvtjkNJc2ar657q9h8XeXuLyCA5nA=
Accept: application/json

> {%
   client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###