---
version: "3"
volumes: { chain-data: {} }
services:
  node:
    image: assetmantle/node:edge
    container_name: mantleNode
    build: .
    volumes: [chain-data:/root/.mantleNode]
    entrypoint: sh
    command:
      - -cex
      - |
        if [[ ! -f ~/.mantleNode/config/config.toml ]]; then
          mantleNode init test --chain-id load-test-1
          mantleNode keys add test --keyring-backend test
          mantleNode add-genesis-account test 10000000000000000000000stake --keyring-backend test
          mantleNode gentx test 1000000000stake --keyring-backend test --chain-id load-test-1
          mantleNode collect-gentxs
        fi
        mantleNode start \
          --rpc.laddr=tcp://0.0.0.0:26657 &
        sleep 99999
