---
version: "3"
services:
  node:
    image: assetmantle/node:edge
    container_name: node
    build: .
    ports:
      - 26657:26657
    entrypoint: bash
    command:
      - -cex
      - |
        mantleNode init test --chain-id load-test-1
        mantleNode keys add test --keyring-backend test
        mantleNode add-genesis-account test 10000000000000000000000stake --keyring-backend test
        mantleNode gentx --name test --amount 1000000000stake --keyring-backend test
        mantleNode collect-gentxs
        mantleNode start \
          --pruning=nothing \
          --rpc.laddr=tcp://0.0.0.0:26657

  client:
    image: assetmantle/node:edge
    container_name: client
    ports:
      - 1317:1317
    build: .
    command:
      - rest-server
      - --keyring-backend=test
      - --node=tcp://node:26657
      - --laddr=tcp://0.0.0.0:1317
      - --trust-node
