name: bugReport🐛
description: Create a report to help us improve
title: "Bug🐛: "
labels: [bug]


body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a Bug report
  - type: textarea
    attributes:
      label: Describe the bug.
      description: "Enter a clear and concise description of what the bug is"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the steps to reproduce the behavior
      description: "Be clear and concise while describing the steps to ensure that it can be reproduced and potentially fixed"
      placeholder: |
        1. Your assetNode version -
        2. assetClient keys add [key_name](add the key name)-
  - type: textarea
    attributes:
      label: Expected behavior.
      description: "Enter a clear and concise description of what you expected to happen"
  - type: textarea
    attributes:
      label: Screenshots.
      description: "If applicable, add screenshots to help explain your problem"
  - type: input
    attributes:
      label: Operating environment
      description: "What operating system and version are you using? If you are running it on Cloud/Cluster do mention about that."
      placeholder: |
        Ubuntu 20.04.1 LTS
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context or screenshots to clarify your suggestion here."