name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2
        with: {install: true}

      - uses: docker/build-push-action@v4
        with:
          tags: assetmantle/node:edge
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TARGETARCH=amd64
            BUILDARCH=amd64
