name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare tags
        id: meta-main-branch
        uses: docker/metadata-action@v3
        with:
          images: |
            assetmantle/node
          tags: |
            type=raw,value=edge-{{sha}}-{{date 'X'}}
            type=raw,value=edge

      - name: Build
        uses: docker/build-push-action@v3
        with:
          tags: ${{ steps.meta-main-branch.outputs.tags }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login to docker registry
        uses: docker/login-action@v1
        if: ${{ github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        if: ${{ github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        with:
          tags: ${{ steps.meta-main-branch.outputs.tags }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
