name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # - uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.19

      - uses: actions/checkout@v2

      - run: make verify

      - uses: docker/setup-buildx-action@v2
        with: {install: true}

      - uses: docker/build-push-action@v4
        with:
          tags: assetmantle/node:edge
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TARGETARCH=amd64
            BUILDARCH=amd64
